parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

# Note: the 'endpoint' refers to the Azure service connection, which can be
# found on the Azure pipelines web interface under
# scipp > scipp > Settings > Service connections

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: main

trigger:
  - main

pr: none

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    config:
      linux:
        py_versions: ['3.7']
        conda_env: 'scipp-developer-linux.yml'
      osx:
        py_versions: ['3.7']
        conda_env: 'scipp-developer-minimal.yml'
      windows:
        py_versions: ['3.7']
        conda_env: 'scipp-developer-minimal.yml'
    deploy: true
    conda_label: 'dev'
