name: Pull request and Main

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  code-quality:
    uses: nvaytet/actions/.github/workflows/code_quality.yml@main
    with:
      pyversion: 3.8
